site_name: Commander
site_description: 'Moderation redefined'
site_author: 'Evo Incorp'
docs_dir: docs/
repo_name: 'Repository'
repo_url: 'https://github.com/evoincorp/commander'
edit_uri: edit/v2/docs
plugins:
  - search
copyright: Copyright &copy; 2020 - 2021 Evo Incorp
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
        guess_lang: false
  - toc:
        permalink: true
  - def_list
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
        smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
        custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.snippets
  - pymdownx.highlight
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
     custom_checkbox: true
theme:
  name: 'material'
  custom_dir: overrides
  font: false
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - toc.integrate
  favicon: assets/images/logo.png
  logo: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to light theme
